### ISSUE TITLE
Fix dominating 2.7.x crashes in production

### ISSUE THREAD

**Issue by defagos** [SRGSSR/playsrg-ios#49]
Currently, a collection view layout issue generates several crashes in production (see e.g. https://rink.hockeyapp.net/manage/apps/105349/app_versions/27/crash_reasons/178105995).

Whichever the BU, the crash always involves 262 items in the collection. In fact, this corresponds to the number of weeks during the last 5 years (can slightly vary). This is therefore an `FSCalendar`crash, probably related to the fact we have set a maximum date, see https://github.com/WenchaoD/FSCalendar/issues/565.

**Comment by defagos** [comment]
Close as duplicate of #108.

**Comment by defagos** [comment]
Looking at crash logs after 2.9.4 has been delivered, it appears that #108 did not fix all calendar-related layout crashes. A few remain. I will still leave this ticket closed since we probably found a good trade-off between the amount of time we could spend on this issue and the stability improvement we obtained.

**Comment by Manibhushan393** [comment]
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0xa5d4e5d00b58b480> {length = 2, path = 1 - 35}   # How to fix the issue in ios 12.4.4 and pod 2.8.0 , xcode 11.2.1 , app crashes
